### ISSUE TITLE
XJog packages in the future

### ISSUE THREAD

**Issue by juhamust** [samihult/xjog#1]
What is the plan and/or timeline for managing XJog packages in the future? 

- Will GH packages be removed?
- Will the project start publishing packages on npmjs.com?

Just thinking if projects using these packages start building XJog packages on their own if no packages are being published by this project. 🤔

**Comment by samihult** [comment]
Happy new year, Juha! 

The goal is to clean up, graduate to beta and publish to npmjs repository all the currently available alpha packages during the January 2023. Hold on tight!

You can join the slack channel [#xjog](https://dossantoshult.slack.com/archives/C04BAEEKX9S) for further discussion and updates.

**Comment by juhamust** [comment]
Likewise! I believe some kind of invitation link for Slack is needed in order to get me there 😊 Please send one using the method most convenient for you 👍
