### ISSUE TITLE
Persitence tables journalEntries + fullJournalStates do not allow actions=null

### ISSUE THREAD

**Issue by juhamust** [samihult/xjog#2]
See:

- https://github.com/samihult/xjog/blob/6a7def650fbbbaf58cf490b37242368ee6ca9ab6/packages/journal-pg/src/PostgresJournalPersistenceAdapter.ts#L130
- https://github.com/samihult/xjog/blob/6a7def650fbbbaf58cf490b37242368ee6ca9ab6/packages/journal-pg/src/migrations/001-initial.sql#L25
- https://github.com/samihult/xjog/blob/837bb1d03ac879c81ce9703b412d30f8d4071188/packages/journal-pg/src/migrations/001-initial.sql#L50

**Comment by samihult** [comment]
Should be fixed in [@samihult/xjog-journal-pg@0.0.109](https://github.com/samihult/xjog/releases/tag/%40samihult%2Fxjog-journal-pg%400.0.109)

**Comment by juhamust** [comment]
Seems to work 👍
